### ISSUE TITLE
Cytotoxicity concern

### ISSUE THREAD

**Issue by alvaro-magalhaes** [StructuralGenomicsConsortium/CNP10-CHIKV-Naphthoquinone#1]
It has been raised some concern regarding the structural similarity of these naphthoquinones to RA-0001914 - from [DENV Rdrp ChEMBL series](https://github.com/StructuralGenomicsConsortium/CNP9-DENVRdrp-ChEMBL/wiki/The-Story-So-Far). RA-0001914 showed cytotoxicity when tested for human mitochondrial RNA production.

<p align="center">
  <img src="https://raw.githubusercontent.com/StructuralGenomicsConsortium/CNP10-CHIKV-Naphthoquinone/main/Wiki%20Files/Issue%201%20Figure.jpeg" />
</p>

The naphthoquinones report show no cytotoxicity when tested in the following conditions: Quote from the paper "The naphthoquinone derivatives cytotoxicity in Vero cells was evaluated using 3-(4,5-dimethylthiazol-2-yl)-2,5 diphenyltetrazolium bromide tetrazolium (MTT) reduction colorimetric assay in 96-well plate and incubated for 24 h at 37 °C.28 After, naphthoquinones derivatives were added in increasing concentrations, ranging from 50 to 1000 µM, diluted in DMEM. After this period, the cells were incubated with the MTT method and evaluated in a microplate reader to determine cell viability. DMSO-treated cells (1.0%) in DMEM were used as control of the evaluation. Determination of cell viability was calculated by percentage comparing treated cells with untreated cells and cells in DMSO" [10.21577/0103-5053.20220010](https://doi.org/10.21577/0103-5053.20220010).

It is important that cytotoxicity is evaluated alongside antiviral activity.

**Comment by mattodd** [comment]
Closing as these data have now been obtained, and this issue has been linked in the Story So Far.
